### ISSUE TITLE
Posizionamento client GraphQL

### ISSUE THREAD

**Issue by bbtgnn** [lascuolaopensource/join#8]
L'obiettivo è inizializzare il client GraphQL una volta sola, in questo modo non si ripete ogni volta la procedura di reinizializzazione.

Reference: https://github.com/timhall/svelte-apollo/issues/97

**Comment by bbtgnn** [comment]
Si potrebbe inserire il client dentro uno store? Da verificare.

**Comment by ZerdoX-x** [comment]
Here is the only way how to make apollo (and svelte-apollo) work with svelte: https://github.com/apollographql/apollo-client/issues/8218#issuecomment-978342041

**Comment by bbtgnn** [comment]
Per il momento `apollo` è stato sostituito da `graphql-request`, molto facile da configurare (con un unico fix da fare indicato [qui](https://sos-nuovo-sito.notion.site/Fix-client-GraphQL-e-altre-librerie-5e7c6912fad14fb689673f8e05ef6a00)).

In ogni caso per ogni componente bisogna creare il client, non sono ancora riuscito a farlo funzionare nel layout. Come soluzione per ridurre la ripetizione di codice ho incapsulato tutto il necessario in un'unica funzione.

**Comment by bbtgnn** [comment]
Closed with #40

**Comment by bbtgnn** [comment]
> non sono ancora riuscito a farlo funzionare nel layout

Il problema sembrerebbe essere dato dall'utilizzo di `setContext`, da indagare. Può sia essere un problema nostro che una limitazione di SvelteKit.

Quindi, ricapitolando: per il momento ogni componente crea un suo client. Se questo diventa troppo impattante a livello di performance si cercherà una soluzione migliore. Per il momento va bene.

**Comment by bbtgnn** [comment]
Al momento il client graphql non è più utilizzato, in quanto non è possibile effettuare call dalla funzione `load` di svelte. Servirebbe la versione server del client graphql, ma per il momento va bene utilizzare fetch.
